=== forever9980/m-d-akecode/meta/psm2code.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/psm2code" xmlns="http://www.example.org/psm2code"
	elementFormDefault="qualified">

	<xs:element name="Root">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Files" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
	</xs:element>

	<xs:element name="Files">
		<xs:complexType>
		    <xs:sequence>
                <xs:element ref="File" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            
			<xs:attribute name="type" type="xs:string" />
        </xs:complexType>
	</xs:element>

	<xs:element name="File" type="xs:string" />
</xs:schema>

=== forever9980/m-d-akecode/meta/psm2f3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns="http://www.example.org/psm2code" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.example.org/psm2code psm2code.xsd ">
        
        <Files type="required">
            <File>f3/AbstractAxonClass.tpl.php</File>
            <File>f3/ConfigFile.tpl.php</File>
            <File>f3/IndexFile.tpl.php</File>
        </Files>
        
        <Files type="interface">
            <File>f3/Interface.tpl.php</File>
        </Files>
        
        <Files type="model">
            <File>f3/StoredModelClass.tpl.php</File>
            <File>f3/ModelClass.tpl.php</File>
        </Files>

        <Files type="database">
            <File>f3/DatabaseSchema.tpl.sql</File>
        </Files>
        
        <Files type="rest">
            <File>f3/RestController.tpl.php</File>
        </Files>
</Root>
